### ISSUE TITLE
Fix laws of robots

### ISSUE THREAD

**Issue by agriffin08** [BallinOuttaControl/bocbot#4]
0. A robot may not harm humanity, or, by inaction, allow humanity to come to harm.
1. A robot may not injure a human being or, through inaction, allow a human being to come to harm.
2. A robot must obey any orders given to it by human beings, except where such orders would conflict with the First Law.
3. A robot must protect its own existence as long as such protection does not conflict with the First or Second Law.

**Comment by agriffin08** [comment]
Zero shouldn't be there

**Comment by Conroman16** [comment]
This was fixed in f466b4b.
